// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatenPottery.Models;

#nullable disable

namespace PatenPottery.Migrations
{
    [DbContext(typeof(PatenPotteryContext))]
    [Migration("20240525111753_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PatenPottery.Models.Code", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("PatenPottery.Models.CustomerDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("PatenPottery.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessFlowID")
                        .HasColumnType("int");

                    b.Property<int>("StatusCD")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("ProcessFlowID")
                        .IsUnique();

                    b.HasIndex("StatusCD")
                        .IsUnique();

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PatenPottery.Models.ProcessFlow", b =>
                {
                    b.Property<int>("ProcessFlowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessFlowID"), 1L, 1);

                    b.Property<bool>("DoFire")
                        .HasColumnType("bit");

                    b.Property<bool>("DoGlaze")
                        .HasColumnType("bit");

                    b.HasKey("ProcessFlowID");

                    b.ToTable("ProcessFlows");
                });

            modelBuilder.Entity("PatenPottery.Models.OrderDetail", b =>
                {
                    b.HasOne("PatenPottery.Models.CustomerDetail", "Customerdetail")
                        .WithOne("OrderDetail")
                        .HasForeignKey("PatenPottery.Models.OrderDetail", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatenPottery.Models.ProcessFlow", "ProcessFlow")
                        .WithOne("OrderDetail")
                        .HasForeignKey("PatenPottery.Models.OrderDetail", "ProcessFlowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatenPottery.Models.Code", "StatusCode")
                        .WithOne("OrderDetail")
                        .HasForeignKey("PatenPottery.Models.OrderDetail", "StatusCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customerdetail");

                    b.Navigation("ProcessFlow");

                    b.Navigation("StatusCode");
                });

            modelBuilder.Entity("PatenPottery.Models.Code", b =>
                {
                    b.Navigation("OrderDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("PatenPottery.Models.CustomerDetail", b =>
                {
                    b.Navigation("OrderDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("PatenPottery.Models.ProcessFlow", b =>
                {
                    b.Navigation("OrderDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
